<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1513266133823' stop='1513266195654'>
    <name>Locator testing By Repeater</name>
    <title>Locator testing By Repeater</title>
    <test-cases>
        <test-case start='1513266133824' status='failed' stop='1513266195653'>
            <name>Validate user credentials</name>
            <title>Validate user credentials</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='a6dd45d4-86b1-4768-b101-cd046bc0266e-attachment.png' type='image/png' size='21742'/>
            </attachments>
            <failure>
                <message>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.</message>
                <stack-trace>Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
                    at Timeout._onTimeout (c:\Users\Deyan\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4281:23)
                    at ontimeout (timers.js:386:14)
                    at tryOnTimeout (timers.js:250:5)
                    at Timer.listOnTimeout (timers.js:214:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>